package airlinetycoon.modelo;

// Generated Nov 13, 2011 7:42:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Avion generated by hbm2java
 */
@Entity
@Table(name = "avion")
public class Avion extends ObjetoDominio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	private long id;
	private String nombre;
	@ManyToOne
	@Basic(fetch=FetchType.LAZY)
	@JoinColumn(name="modelo_id",referencedColumnName="id")
	private Modeloavion modelo;
	private int antiguedad;
	private int kilometros_recorridos;
	@ManyToOne
	@Basic(fetch=FetchType.LAZY)
	@JoinColumn(name="ubicacion",referencedColumnName="id")
	private Aeropuerto ubicacion;
	private EstadoAvion estado;
	private AlertaAvion alerta;
	@ManyToOne
	@JoinColumn(name="aerolinea_id")
	private Aerolinea aerolinea;
	@Transient
	private Posicion posicion;

	public Avion() 
	{
		estado=EstadoAvion.TIERRA;
		alerta=AlertaAvion.NORMAL;
	}

	public Avion(String nombre, Modeloavion modelo, int antiguedad,
			int kilometrosRecorridos) 
	{
		this.nombre = nombre;
		this.modelo = modelo;
		this.antiguedad = antiguedad;
		this.kilometros_recorridos= kilometrosRecorridos;
	}

	public long getId() 
	{
		return this.id;
	}

	public void setId(Integer id) 
	{
		this.id = id;
	}


	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() 
	{
		return this.nombre;
	}

	public void setNombre(String nombre) 
	{
		this.nombre = nombre;
	}

	public Modeloavion getModeloId() 
	{
		return this.modelo;
	}

	public void setModeloId(Modeloavion modelo) 
	{
		this.modelo = modelo;
	}

	@Column(name = "antiguedad", nullable = false)
	public int getAntiguedad() 
	{
		return this.antiguedad;
	}

	public void setAntiguedad(int antiguedad) 
	{
		this.antiguedad = antiguedad;
	}

	@Column(name = "kilometros_recorridos", nullable = false)
	public int getKilometros_recorridos() 
	{
		return this.kilometros_recorridos;
	}

	public void setKilometros_recorridos(int kilometrosRecorridos) 
	{
		this.kilometros_recorridos= kilometrosRecorridos;
	}
	public Aeropuerto getUbicacion() 
	{
		return ubicacion;
	}
	
	public void setUbicacion(Aeropuerto ubicacion) 
	{
		this.ubicacion = ubicacion;
	}
	public String toString()
	{
		return this.nombre;
	}

	public Posicion getPosicion()
	{
		return posicion;
	}

	public void setPosicion(Posicion posicion)
	{
		this.posicion = posicion;
	}

	public EstadoAvion getEstado() {
		return estado;
	}

	public void setEstado(EstadoAvion estado) {
		this.estado = estado;
	}

	public AlertaAvion getAlerta() {
		return alerta;
	}

	public void setAlerta(AlertaAvion alerta) {
		this.alerta = alerta;
	}

	public Aerolinea getAerolinea() {
		return aerolinea;
	}

	public void setAerolinea(Aerolinea aerolinea) {
		this.aerolinea = aerolinea;
	}

}
