package airlinetycoon.modelo;

// Generated Nov 13, 2011 7:42:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name = "vuelo")
public class Vuelo extends ObjetoDominio implements java.io.Serializable 
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Ciudad origen;
	private Ciudad destino;
	private double pago;
	private int pasajeros;

	public Vuelo() {
	}

	public Vuelo(Ciudad origenId, Ciudad destinoId, double pago, int cantPasajeros) {
		this.origen = origenId;
		this.destino = destinoId;
		this.pago = pago;
		this.pasajeros = cantPasajeros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@Basic(fetch=FetchType.LAZY)
	@JoinColumn(name="origen_id",referencedColumnName="id")
	public Ciudad getOrigen() {
		return this.origen;
	}

	public void setOrigen(Ciudad origenId) {
		this.origen = origenId;
	}

	@ManyToOne
	@Basic(fetch=FetchType.LAZY)
	@JoinColumn(name="destino_id",referencedColumnName="id")
	public Ciudad getDestino() {
		return this.destino;
	}

	public void setDestino(Ciudad destinoId) {
		this.destino = destinoId;
	}

	@Column(name = "pago", nullable = false, precision = 22, scale = 0)
	public double getPago() {
		return this.pago;
	}

	public void setPago(double pago) {
		this.pago = pago;
	}

	@Column(name = "pasajeros", nullable = false)
	public int getPasajeros() {
		return this.pasajeros;
	}

	public void setPasajeros(int cantPasajeros) {
		this.pasajeros = cantPasajeros;
	}

}
