ALTER TABLE `ciudad` DROP `codigo`;
INSERT INTO `aeropuerto` (`ciudad_id`, `codigo`, `nombre`) VALUES
(1, 'LGW', 'London Gatwick'),
(2, 'GIG', 'Rio de Janeiro Tom Jobim'),
(3, 'LIM', 'Jorge Chavez international airport'),
(4, 'ULC', 'Los Cerrillos airport'),
(5, 'BOG', 'El Dorado international airpor'),
(6, 'MIA', 'Miami international airport'),
(7, 'ATL', 'Hartsfield-Jackson Atlanta international airport'),
(8, 'JFK', 'John Fitzgerald Kennedy New York international airport'),
(9, 'DEN', 'Denver International Airport'),
(10, 'LAX', 'Los Angeles International Airport'),
(11, 'SFO', 'San Francisco International airport'),
(12, 'SIN', 'Singapore Changi international airport'),
(13, 'ICN', 'Incheon International Airport'),
(14, 'NRT', 'Tokyo Narita international Airport'),
(15, 'MNL', 'Ninoy Aquino (Manila) International Airport'),
(16, 'BOM', 'Chatrapati Shivaji international airport'),
(17, 'CCU', 'Netaji Shubash Chandra international airport'),
(18, 'BKK', 'Suvarnabhumi Airport'),
(19, 'IST', 'Istanbul Airport'),
(20, 'PRG', 'Prague Vaclav Havel Airport'),
(21, 'CDG', 'Paris Charles de Gaulle Airport'),
(22, 'ORD', 'Chicago O\'Hare Airport'),
(23, 'ZRH', 'Zurich Airport'),
(24, 'FRA', 'Frankfurt international airport'),
(25, 'SVO', 'Seremetyevo Moscow international airport'),
(26, 'MSQ', 'Minsk International airport'),
(27, 'SYD', 'Sydney Airport'),
(28, 'EZE', 'Ministro Pistarini Airport'),
(29, 'JNB', 'OR Tambo international airport'),
(30, 'NBO', 'Jomo Kenyatta international airport'),
(31, 'DKR', 'Leopold Sedar Senghor international airport'),
(32, 'CPT', 'Cape Town international airport');
